# cPanel Git deployment config
# Deploy the production build from ./dist
deployment:
  tasks:
    - export DEPLOYPATH="${HOME}/public_html/"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "$DEPLOYPATH"/*
    - /bin/cp -a ./dist/. "$DEPLOYPATH"
